import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { faGhost } from "../../node_modules/@fortawesome/free-solid-svg-icons/index";
import { FontAwesomeIcon } from "../../node_modules/@fortawesome/react-fontawesome/index";
import Link from "../../node_modules/next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mb-16">
          <div className=" flex justify-between max-w-3xl mx-auto px-4 py-2">
            <Link href={"/"} className="inline-flex gap-1 items-center ">
              <FontAwesomeIcon className="h-8 text-yellow-400" icon={faGhost} />
              <span className="mt-1">pick a boo</span>
            </Link>
            <nav className="mt-1 items-center flex gap-6">
              <Link href={"/about"}> About</Link>
              <Link href={"/explore"}>Explore</Link>
              <div className="gap-2 flex">
                <button className="bg-slate-100 rounded-full px-4 py-1.5 ml-3 ">
                  Log In
                </button>
                <button className="bg-yellow-300 rounded-full px-4 py-1.5 ">
                  Sign Up
                </button>
              </div>
            </nav>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
